api_platform:
    title: 'MicroDonjon API'
    description: 'Accédez à toutes les ressources du jeu textuel MicroDonjon'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

